name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"
INIT_TABLE=true
ENABLE_CACHE=true

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "4cdf26c5-5450-408c-9885-e4f0e50dfb94"
